name: 'dbt_test_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ADD THIS BLOCK TO FIX THE WARNING
flags:
  use_materialization_v2: true

models:
  dbt_test_project:
    +materialized: table
